#TODO: remove?
USE SCRIBBLE;

DROP TABLE IF EXISTS users;
CREATE TABLE users (
    ID INT NOT NULL,
    USERNAME VARCHAR(32) NOT NULL,
    PASSWORD VARCHAR(256) NOT NULL
);

DROP TABLE IF EXISTS games;
CREATE TABLE games (
    ID INT NOT NULL,
    DATE DATE,
    WINNER_ID INT,
    WINNING_SCORE INT,
    SCORED BIT
);
